const BASE_POINTS = 7000; // Base points before this sequence of tournaments

/**
 * Initializes the Dashboard by fetching data from the JSON database
 */
async function initDashboard() {
    try {
        // Fetch data from the data.json file generated by our bot
        const response = await fetch('data.json');
        const data = await response.json();
        
        // Render table, chart, and update total points dynamically
        renderTableAndPoints(data.tournaments, data.total_points);
        renderChart(data.tournaments);
        
        // Log the last update time to the console
        console.log(`Data last updated: ${data.last_updated}`);
        
    } catch (error) {
        console.error("Error loading Sinner stats:", error);
    }
}

/**
 * Calculates net differences and populates the HTML table
 */
function renderTableAndPoints(tournaments, totalPoints) {
    const tableBody = document.getElementById('tournament-data');
    let htmlContent = '';

    tournaments.forEach(t => {
        const diff = t.earned - t.defending;
        let diffColor = diff >= 0 ? 'text-sinner-green' : 'text-red-500';
        let sign = diff >= 0 ? '+' : '';

        htmlContent += `
            <tr class="border-b border-gray-100 transition duration-150">
                <td class="py-4 px-6 text-sinner-orange font-bold">${t.name}</td>
                <td class="py-4 px-6 text-center text-gray-400">${t.defending}</td>
                <td class="py-4 px-6 text-center font-bold">${t.earned}</td>
                <td class="py-4 px-6 text-center font-black ${diffColor}">${sign}${diff}</td>
            </tr>
        `;
    });

    tableBody.innerHTML = htmlContent;
    
    // Update the total points display
    const pointsDisplay = document.getElementById('total-points-display');
    if(pointsDisplay) {
        pointsDisplay.innerText = totalPoints;
    }
}

/**
 * Renders the line chart with Chart.js
 */
function renderChart(tournaments) {
    const ctxElement = document.getElementById('pointsChart');
    if (!ctxElement) return;

    const ctx = ctxElement.getContext('2d');
    const labels = [];
    const pointsData = [];
    let runningTotal = BASE_POINTS;

    tournaments.forEach(t => {
        runningTotal += (t.earned - t.defending);
        labels.push(t.name);
        pointsData.push(runningTotal);
    });

    // Destroy existing chart instance if it exists to avoid overlap bugs
    if(window.sinnerChart) {
        window.sinnerChart.destroy();
    }

    window.sinnerChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [{
                label: 'Cumulative ATP Points',
                data: pointsData,
                borderColor: '#f97316',
                backgroundColor: 'rgba(249, 115, 22, 0.1)',
                fill: true,
                tension: 0.4,
                borderWidth: 4,
                pointBackgroundColor: '#171717',
                pointBorderColor: '#ffffff',
                pointBorderWidth: 2,
                pointRadius: 6,
                pointHoverRadius: 8
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: { 
                legend: { display: false },
                tooltip: {
                    backgroundColor: '#171717',
                    titleFont: { family: 'Montserrat', size: 14 },
                    bodyFont: { family: 'Montserrat', size: 14, weight: 'bold' },
                    padding: 12,
                    displayColors: false
                }
            },
            scales: {
                y: { 
                    grid: { color: '#f1f5f9' }, 
                    ticks: { font: { family: 'Montserrat', weight: '600' } } 
                },
                x: { 
                    grid: { display: false }, 
                    ticks: { font: { family: 'Montserrat', weight: '600' } } 
                }
            }
        }
    });
}

// --- TROPHY CABINET LOGIC ---

// Trophy database (you can move this to data.json in the future!)
const trophies = [
    { title: "Australian Open", year: 2024, category: "Grand Slam", surface: "Hard" },
    { title: "Miami Open", year: 2024, category: "Masters 1000", surface: "Hard" },
    { title: "Rotterdam", year: 2024, category: "ATP 500", surface: "Hard (Indoor)" },
    { title: "Davis Cup", year: 2023, category: "Team", surface: "Hard (Indoor)" },
    { title: "Toronto", year: 2023, category: "Masters 1000", surface: "Hard" },
    { title: "Vienna", year: 2023, category: "ATP 500", surface: "Hard (Indoor)" },
    { title: "Beijing", year: 2023, category: "ATP 500", surface: "Hard" }
];

/**
 * Generates the HTML for the trophy cabinet
 */
function renderTrophies() {
    const cabinet = document.getElementById('trophy-cabinet');
    if (!cabinet) return;

    let htmlContent = '';

    trophies.forEach(t => {
        let bgClass = "bg-white";
        let borderClass = "border-sinner-black";
        let icon = "🏆";
        
        if (t.category === "Grand Slam") {
            bgClass = "bg-gradient-to-br from-yellow-50 to-orange-100";
            borderClass = "border-yellow-400";
            icon = "👑"; 
        } else if (t.category === "Masters 1000") {
            borderClass = "border-sinner-orange";
        }

        htmlContent += `
            <div class="p-5 rounded-xl shadow-md border-b-4 ${borderClass} ${bgClass} transition-transform hover:-translate-y-2 duration-300 text-center flex flex-col justify-between min-h-[160px]">
                <div>
                    <div class="text-4xl mb-3 drop-shadow-md">${icon}</div>
                    <h4 class="font-bold text-sinner-black leading-tight text-sm">${t.title}</h4>
                </div>
                <div class="mt-4">
                    <span class="inline-block bg-sinner-black text-sinner-white text-[10px] px-2 py-1 rounded uppercase tracking-wider font-bold">${t.category}</span>
                    <p class="text-sinner-orange font-black mt-2 text-lg">${t.year}</p>
                </div>
            </div>
        `;
    });

    cabinet.innerHTML = htmlContent;
}

// --- H2H RIVALRIES LOGIC ---

// Database of main rivals (Update these numbers as the season progresses!)
const rivalsData = [
    { name: "Carlos Alcaraz", wins: 4, losses: 5, country: "🇪🇸" },
    { name: "Novak Djokovic", wins: 3, losses: 4, country: "🇷🇸" },
    { name: "Daniil Medvedev", wins: 5, losses: 6, country: "🏳️" }
];

/**
 * Generates HTML for the Head-to-Head cards with dynamic progress bars
 */
function renderH2H() {
    const container = document.getElementById('h2h-container');
    if (!container) return;

    let htmlContent = '';

    rivalsData.forEach(rival => {
        const totalMatches = rival.wins + rival.losses;
        // Calculate Sinner's win percentage to fill the bar
        const winPercentage = totalMatches === 0 ? 0 : Math.round((rival.wins / totalMatches) * 100);
        
        // Determine text color based on who is leading the H2H
        let statusColor = "text-gray-500";
        if (rival.wins > rival.losses) {
            statusColor = "text-sinner-green"; // Sinner is leading
        } else if (rival.wins < rival.losses) {
            statusColor = "text-red-500"; // Rival is leading
        }

        htmlContent += `
            <div class="bg-white p-6 rounded-xl shadow-md border border-gray-100 transition-transform hover:-translate-y-2 duration-300">
                <div class="flex justify-between items-center mb-4">
                    <h4 class="font-bold text-lg text-sinner-black">${rival.name} ${rival.country}</h4>
                    <span class="text-2xl font-black ${statusColor}">${rival.wins} - ${rival.losses}</span>
                </div>
                
                <div class="w-full bg-gray-200 rounded-full h-3 mb-2 flex overflow-hidden">
                    <div class="bg-sinner-orange h-3" style="width: ${winPercentage}%"></div>
                    <div class="bg-sinner-black h-3" style="width: ${100 - winPercentage}%"></div>
                </div>
                
                <div class="flex justify-between text-xs font-bold text-gray-400 uppercase tracking-wider">
                    <span>Sinner (${winPercentage}%)</span>
                    <span>Opponent</span>
                </div>
            </div>
        `;
    });

    container.innerHTML = htmlContent;
}

// --- GLOBAL INITIALIZATION ---
// This is the ONLY EventListener needed when the page loads
document.addEventListener('DOMContentLoaded', () => {
    initDashboard();
    renderTrophies();
    renderH2H();
});